### ISSUE TITLE
Summary 

### ISSUE THREAD

**Issue by davecastlevania** [andre-moore/intro-data-capstone-musclehub#4]
You did a great job on this project. It is apparent to me that you have a good handle on how datascience works in relation to Python and SQL databases. Great job, I thoroughly enjoyed you presentation. You were very well detailed and I appreciated that you include snippets of code throughout your examples showing how you would get certain results. Great job! If you wanna put together a portfolio you now have tools at your disposal that you can use with open datasets that you can make presentations for. Feel free to include this one in your portfolio. Keep it up. 

Open Data Sets:
https://www.analyticsvidhya.com/blog/2016/11/25-websites-to-find-datasets-for-data-science-projects/

Summary: Beyond Expectation

**Comment by andre-moore** [comment]
Thank you Dave! I appreciate your comments. What are next steps? Thanks!
